version: "3.8"

networks:
  elasticsearch-net:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_STACK_VERSION}
    container_name: elasticsearch
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elasticsearch-net
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_STACK_VERSION}
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elasticsearch-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_STACK_VERSION}
    container_name: logstash
    volumes:
      - ./logstash-data/pipeline/:/usr/share/logstash/pipeline/
    networks:
      - elasticsearch-net
    depends_on:
      - elasticsearch
    ports:
      - 5044:5044

  grafana:
    image: grafana/grafana-oss:9.5.1
    container_name: grafana
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks: 
      - elasticsearch-net
    ports:
      - 3000:3000
