version: "3.8"

services:
  grafana:
    image: grafana/grafana:7.2.0
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    restart: "no"
