version: "3.8"

services:
  splunk:
    image: splunk/splunk
    container_name: splunk
    restart: "no"
    ports:
      - 8000:8000
    environment:
      - SPLUNK_PASSWORD=pwdokiet2017#.
      - SPLUNK_START_ARGS=--accept-license
