version: "3.8"

services:
  haproxy:
    image: registry-proxy.flowti.com.br/haproxy:2.6.1-alpine
    container_name: haproxy
    restart: "no"
    ports:
      - 8080:8080
      - 1936:1936
    volumes:
      - ./cfg/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./errors:/usr/local/etc/haproxy/custom-errors
