version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
    restart: "no"
